/**
 * The domain rules of the Competition module and its public interface (Unit 03).
 * Other modules call this service, never the repository (invariant 4).
 *
 * What lives here: creating a competition and auto-building its fixed 2-stage ×
 * 2-round structure with the documented defaults, editing it before publish, the
 * four-condition publish readiness check, publishing, and the structure lock.
 *
 * Two decisions worth stating:
 * - The stages are the schema's: exactly two per *competition* (Individual then
 *   Team), with round settings set once per round for the whole event, not per
 *   category (data-model.md, RND-005; CS-010). Categories are created alongside;
 *   they run in parallel against the same structure.
 * - The two link tokens are generated by the schema's `@default(uuid())` when the
 *   competition row is created, so publish surfaces them rather than creating them
 *   (Unit 03 spec, Implementation Details 4).
 */
import { now } from "../../shared/clock";
import {
  ConflictError,
  NotFoundError,
  UnprocessableEntityError,
  ValidationError,
} from "../../shared/errors";
import { translate } from "../../shared/i18n";
import * as repository from "./competition.repository";
import type { CompetitionWithStructure } from "./competition.repository";
import {
  defaultDurationSeconds,
  isStructureLocked,
  STAGE_SEQUENCE,
  type CategoryInput,
  type CreateCompetitionInput,
  type PublishResult,
  type ReadinessCondition,
  type ReadinessResult,
  type RoundSettingsPatch,
  type UpdateCompetitionInput,
} from "./competition.types";

const STAGE_ROUND_COUNT = 2;

/**
 * An Individual round uses exactly 6 selected questions (competition-rules.md §2;
 * BLD-040). The publish readiness check requires all 6 assigned per Individual round.
 */
const INDIVIDUAL_ROUND_QUESTION_COUNT = 6;

const ROUND_NAME: Record<string, string> = {
  "INDIVIDUAL:1": "Individual round 1",
  "INDIVIDUAL:2": "Individual round 2",
  "TEAM:1": "Team round 1",
  "TEAM:2": "Team round 2",
};

function lockedError(): ConflictError {
  return new ConflictError(translate("en", "competition.structureLocked"), {
    code: "competition.structureLocked",
  });
}

function notFoundError(): NotFoundError {
  return new NotFoundError(translate("en", "competition.notFound"), {
    code: "competition.notFound",
  });
}

function condition(
  key: ReadinessCondition["key"],
): ReadinessCondition {
  return { key, message: translate("en", key) };
}

// ---------------------------------------------------------------------------
// Round-settings validation (SCR-012: whole numbers; times and counts above zero)
// ---------------------------------------------------------------------------

/** Fields that are a duration or a count and therefore must be a positive whole number. */
const POSITIVE_FIELDS: (keyof RoundSettingsPatch)[] = [
  "durationSeconds",
  "preparationSeconds",
  "rotationPeriodSeconds",
  "teamQuestionCount",
  "teamTotalTimeSeconds",
  "partitionPuzzleCount",
  "partitionTotalTimeSeconds",
];

/** Fields that are a score and therefore must be at least 1. */
const AT_LEAST_ONE_FIELDS: (keyof RoundSettingsPatch)[] = [
  "teamPointsPerQuestion",
  "partitionPointsPerPuzzle",
];

/** Fields that are a threshold and may be zero but not negative. */
const NON_NEGATIVE_FIELDS: (keyof RoundSettingsPatch)[] = [
  "earlyBonusRate",
  "earlyBonusCap",
  "individualTotalWarning",
];

/**
 * Enforce the decided numeric constraints on a round-settings patch. Throws a
 * `ValidationError` naming the offending fields, rather than silently coercing.
 */
export function validateRoundSettingsPatch(patch: RoundSettingsPatch): void {
  const problems: Record<string, string> = {};

  for (const field of POSITIVE_FIELDS) {
    const value = patch[field];
    if (value === undefined || value === null) continue;
    if (!Number.isInteger(value) || value <= 0) {
      problems[field] = "must be a whole number above zero";
    }
  }
  for (const field of AT_LEAST_ONE_FIELDS) {
    const value = patch[field];
    if (value === undefined || value === null) continue;
    if (!Number.isInteger(value) || value < 1) {
      problems[field] = "must be a whole number of at least 1";
    }
  }
  for (const field of NON_NEGATIVE_FIELDS) {
    const value = patch[field];
    if (value === undefined || value === null) continue;
    if (!Number.isInteger(value) || value < 0) {
      problems[field] = "must be a whole number of at least 0";
    }
  }

  if (Object.keys(problems).length > 0) {
    throw new ValidationError("Invalid round settings", problems);
  }
}

// ---------------------------------------------------------------------------
// Creation
// ---------------------------------------------------------------------------

/**
 * The fixed structure every competition gets: two stages (Individual, Team), each
 * with two rounds, each round's settings at their documented defaults, including
 * the schema-required `durationSeconds` (1200 / 1800 / 1800 / 1800).
 */
function buildStructure(): repository.StageStructureInput[] {
  return STAGE_SEQUENCE.map((type, stageIndex) => ({
    type,
    sequence: stageIndex + 1,
    rounds: Array.from({ length: STAGE_ROUND_COUNT }, (_unused, roundIndex) => {
      const sequence = roundIndex + 1;
      return {
        sequence,
        name: ROUND_NAME[`${type}:${sequence}`] ?? `${type} round ${sequence}`,
        durationSeconds: defaultDurationSeconds(type, sequence),
      };
    }),
  }));
}

/** Normalize the input category list into the ordered rows to create. */
function buildCategories(categories: CategoryInput[]): repository.CategoryStructureInput[] {
  return categories.map((category, index) => ({
    code: category.code,
    name: category.name,
    sequence: index + 1,
  }));
}

export async function createCompetition(
  input: CreateCompetitionInput,
): Promise<CompetitionWithStructure> {
  if (input.categories.length === 0) {
    // The controller's schema also rejects this; the rule lives here too.
    throw new ValidationError("At least one category is required", {
      categories: "must contain at least one category",
    });
  }

  return repository.createCompetition({
    name: input.name,
    description: input.description ?? null,
    categories: buildCategories(input.categories),
    stages: buildStructure(),
  });
}

// ---------------------------------------------------------------------------
// Editing (pre-publish for the structure; round settings per the existing rule)
// ---------------------------------------------------------------------------

/**
 * Edit a competition. Name/description and the category list are pre-publish only
 * (the structure is locked after publish); round-settings edits are allowed any time
 * within this unit's scope (the per-round-preparation cutoff is Unit 07's).
 */
export async function updateCompetition(
  id: string,
  input: UpdateCompetitionInput,
): Promise<CompetitionWithStructure> {
  const existing = await repository.findCompetitionById(id);
  if (!existing) {
    throw notFoundError();
  }

  const locked = isStructureLocked(existing.status);

  // Name and description are metadata, not structure — they stay editable.
  if (input.name !== undefined || input.description !== undefined) {
    await repository.updateCompetitionMeta(id, {
      ...(input.name !== undefined ? { name: input.name } : {}),
      ...(input.description !== undefined ? { description: input.description } : {}),
    });
  }

  if (input.categories !== undefined) {
    if (locked) {
      throw lockedError();
    }
    await applyCategoryChanges(id, existing, input.categories);
  }

  if (input.roundSettings !== undefined) {
    for (const [roundId, patch] of Object.entries(input.roundSettings)) {
      await updateRoundSettings(id, roundId, patch);
    }
  }

  const updated = await repository.findCompetitionById(id);
  if (!updated) {
    throw notFoundError();
  }
  return updated;
}

/** Work out the add/remove/reorder plan by matching categories on their code. */
async function applyCategoryChanges(
  competitionId: string,
  existing: CompetitionWithStructure,
  categories: CategoryInput[],
): Promise<void> {
  const wantedCodes = new Set(categories.map((category) => category.code));
  const deleteIds = existing.categories
    .filter((category) => !wantedCodes.has(category.code))
    .map((category) => category.id);

  const byCode = new Map(existing.categories.map((category) => [category.code, category]));
  const create: repository.CategoryStructureInput[] = [];
  const update: { id: string; name: string; sequence: number }[] = [];

  categories.forEach((category, index) => {
    const current = byCode.get(category.code);
    if (current) {
      update.push({ id: current.id, name: category.name, sequence: index + 1 });
    } else {
      create.push({ code: category.code, name: category.name, sequence: index + 1 });
    }
  });

  await repository.applyCategoryChanges(competitionId, { create, update, deleteIds });
}

/** Edit one round's numeric settings, after checking the round belongs to this competition. */
async function updateRoundSettings(
  competitionId: string,
  roundId: string,
  patch: RoundSettingsPatch,
): Promise<void> {
  const round = await repository.findRoundWithCompetition(roundId);
  if (!round || round.stage.competitionId !== competitionId) {
    throw notFoundError();
  }
  validateRoundSettingsPatch(patch);
  if (Object.keys(patch).length > 0) {
    await repository.updateRoundSettings(roundId, patch);
  }
}

// ---------------------------------------------------------------------------
// Publish readiness (four named conditions; later units add their own)
// ---------------------------------------------------------------------------

/**
 * Evaluate the four readiness conditions and return every unmet one (not just the
 * first). The result is a list, so a later unit can plug its condition in here.
 */
export async function checkPublishReadiness(
  competitionId: string,
): Promise<ReadinessResult> {
  const competition = await repository.findCompetitionById(competitionId);
  if (!competition) {
    throw notFoundError();
  }

  const unmet: ReadinessCondition[] = [];

  // 1. At least one category.
  if (competition.categories.length === 0) {
    unmet.push(condition("competition.readiness.categoryRequired"));
  }

  // 2. Every category has at least one participant.
  const participantCategoryIds = new Set(
    (await repository.listActiveParticipantCategoryIds(competitionId)).map(
      (row) => row.categoryId,
    ),
  );
  if (competition.categories.some((c) => !participantCategoryIds.has(c.id))) {
    unmet.push(condition("competition.readiness.participantsRequired"));
  }

  // 3. Every category has a complete question set assigned to both Individual rounds.
  // Since BLD-040 made `Question.roundId` nullable, an imported question sits in the
  // pool unassigned until the controller's manual round-selection step (Unit 05) picks
  // exactly 6 per Individual round. So "covered" now means the full 6 are assigned to
  // that round (roundId set), not merely that some question references it — an empty or
  // partial selection is not publish-ready.
  const individualStage = competition.stages.find((stage) => stage.type === "INDIVIDUAL");
  const individualRoundIds = (individualStage?.rounds ?? []).map((round) => round.id);
  if (individualRoundIds.length < STAGE_ROUND_COUNT) {
    unmet.push(condition("competition.readiness.questionsRequired"));
  } else {
    for (const category of competition.categories) {
      const countByRound = new Map(
        (await repository.countCategoryQuestionsPerRound(category.id)).map((row) => [
          row.roundId,
          row.count,
        ]),
      );
      const complete = individualRoundIds.every(
        (roundId) => (countByRound.get(roundId) ?? 0) === INDIVIDUAL_ROUND_QUESTION_COUNT,
      );
      if (!complete) {
        unmet.push(condition("competition.readiness.questionsRequired"));
        break;
      }
    }
  }

  // 4. Judge ranges cover every active participant number.
  const participantNumbers = (
    await repository.listActiveParticipantNumbers(competitionId)
  ).map((row) => row.participantNumber);
  if (participantNumbers.length > 0) {
    const ranges = await repository.listJudgeRanges(competitionId);
    const uncovered = participantNumbers.some(
      (number) =>
        !ranges.some(
          (range) =>
            number >= range.fromParticipantNumber && number <= range.toParticipantNumber,
        ),
    );
    if (uncovered) {
      unmet.push(condition("competition.readiness.judgeRangesRequired"));
    }
  }

  return { ready: unmet.length === 0, unmet };
}

// ---------------------------------------------------------------------------
// Publish
// ---------------------------------------------------------------------------

/**
 * Publish the competition. Refuses with the specific unmet conditions (HTTP 422,
 * handled by the controller) and makes no state change if any fails; otherwise moves
 * the status `PUBLISHED` → `WAITING`, sets `publishedAt`, and returns the two links
 * that already exist. Publishing more than once is rejected.
 */
export async function publishCompetition(id: string): Promise<PublishResult> {
  const competition = await repository.findCompetitionById(id);
  if (!competition) {
    throw notFoundError();
  }

  if (isStructureLocked(competition.status)) {
    // Already published (or beyond): publishing again is not allowed.
    throw new ConflictError("This competition is already published.", {
      code: "competition.alreadyPublished",
      details: { status: competition.status },
    });
  }

  const readiness = await checkPublishReadiness(id);
  if (!readiness.ready) {
    throw new UnprocessableEntityError("The competition is not ready to publish.", {
      code: "competition.notReady",
      details: { unmet: readiness.unmet },
    });
  }

  const publishedAt = now();
  const updated = await repository.markPublished(id, publishedAt);

  return {
    id: updated.id,
    status: updated.status,
    publishedAt: updated.publishedAt?.toISOString() ?? publishedAt.toISOString(),
    entryLinkToken: updated.entryLinkToken,
    bigScreenLinkToken: updated.bigScreenLinkToken,
  };
}

// ---------------------------------------------------------------------------
// Reads (Unit 11's controller dashboard needs to pick a competition and then read
// its structure to know which commands are legal right now)
// ---------------------------------------------------------------------------

/** Every competition, newest first — the dashboard's picker list. */
export async function listCompetitions(): Promise<
  Awaited<ReturnType<typeof repository.listCompetitions>>
> {
  return repository.listCompetitions();
}

/**
 * One competition with its full structure (categories, stages, rounds, round
 * settings, scoring configuration) — the same shape create/update return, so the
 * dashboard reads exactly what it would have gotten when it created the thing.
 * 404s on an unknown id.
 */
export async function getCompetition(id: string): Promise<CompetitionWithStructure> {
  const competition = await repository.findCompetitionById(id);
  if (!competition) {
    throw notFoundError();
  }
  return competition;
}

// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

export const competitionService = {
  createCompetition,
  updateCompetition,
  checkPublishReadiness,
  publishCompetition,
  validateRoundSettingsPatch,
  listCompetitions,
  getCompetition,
};
